### ISSUE TITLE
Escaping special characters

### ISSUE THREAD

**Issue by swesley** [foex-open-source/fos-redirect#3]
If I redirect using a static URL where the value is
`\&P1_ITEM.\`
Any value surrounded by quotes
`"scott"`
will be replaced with when rendering on the called page
`&quot;scott&quot; `

If I use PL/SQL as the URL source, the item value is rendered with quotes as expected.

If I modify the first else statement of the get_url function to not escape special characters, the value is also rendered as expected.
`l_url := apex_plugin_util.replace_substitutions(l_url, false);`
but I wonder about the potential ramifications of not escaping these characters, and why the PL/SQL method is ok

**Comment by swesley** [comment]
Another alternative is to unescape the input as a before header computation on the called page
`utl_i18n.unescape_reference(:p1_item)`
This causes less problems when XSS testing with
`<script>window.alert('hi');</script>`

**Comment by mnolan866** [comment]
Can you please provide a test case on apex.oracle.com so we can investigate your setup?

**Comment by foex-open-source** [comment]
Fixed in just published v21.1.0
